package me.Jonathon594.Mythria.Enum;

public enum AttributeFlag {
    ATHEISM, ELF_HEALING, HEAVY_ARMOR_ABILITY_CONDITIONING, COOKING2, FIREMAKING1, CARPENTRY, BASIC_COOKING, FISHING, SMELTING, BASIC_SMITHING, ADVANCED_SMITHING, SOPHISTICATED_SMITHING, SMELTING_2, BASIC_GLASSBLOWING, SUPERIOR_SMITHING, MASTERLY_SMITHING, ARTISAN_SMITHING, DWARF_DIGGING, FAE_FLIGHT, SEE_NUTRITION, COOKING_ROASTING, COOKING_BAKING, COOKING_BOILING, FIREMAKING2, PRIMITIVE_FURNACES, BASIC_SMELTING, IMMORTALITY
}
