package me.Jonathon594.Mythria.Enum;

public enum AttributeFlag {
    ATHEISM, ELF_HEALING, HEAVY_ARMOR_ABILITY_CONDITIONING, COOKING2, FIREMAKING1, CARPENTRY, BASIC_COOKING, FISHING, SMELTING, BASIC_SMITHING,
    ADVANCED_SMITHING, SOPHISTICATED_SMITHING, SMELTING_2, BASIC_GLASSBLOWING, SUPERIOR_SMITHING, MASTERLY_SMITHING, ARTISAN_SMITHING, DWARF_DIGGING,
    FAE_FLIGHT, SEE_NUTRITION, COOKING_ROASTING, COOKING_BAKING, COOKING_BOILING, FIREMAKING2, PRIMITIVE_FURNACES, BASIC_SMELTING, SHIELD_ABILITY_BASH,
    HAMMER_ABILITY_LEG_STRIKE, DAGGER_ABILITY_SWIFT_STRIKE, AXE_ABILITY_DOUBLE_AXE, SWORD_ABILITY_HEADSHOT, AXE_ABILITY_CRIT, AXE_ABILITY_HEADSHOT,
    AXE_ABILITY_SWEEP, DAGGER_ABILITY_ANKLE_CUTTER, DAGGER_ABILITY_ASSASSINATE, DAGGER_ABILITY_CHINK, SWORD_ABILITY_DISARM, HAMMER_ABILITY_SHATTER,
    AXE_ABILITY_RAGE, DAGGER_ABILITY_SLICE, SWORD_ABILITY_COUNTERSTRIKE, UNARMED_ABILITY_PARRY, DAGGER_ABILITY_CRIT, DAGGER_ABILITY_KNEE_SLASH,
    DAGGER_ABILITY_SLASH, DAGGER_ABILITY_STAB, DAGGER_ABILITY_SWEEP, DAGGER_ABILITY_TENDON_CUT, DAGGER_ABILITY_THROAT_SLICE, DAGGER_ABILITY_PARRY, HAMMER_ABILITY_HEADSHOT,
    HAMMER_ABILITY_CRIT, HAMMER_ABILITY_DECAPITATE, HAMMER_ABILITY_DENT, HAMMER_ABILITY_DOUBLE_STRIKE, HAMMER_ABILITY_SAVAGERY, SWORD_STAGGER,
    UNARMED_ABILITY_PRESSURE_POINT, SWORD_ABILITY_CRIT, SWORD_ABILITY_LEG_STRIKE, SWORD_SERRATED_STRIKE, SWORD_ABILITY_SWEEP, UNARMED_ABILITY_FACE_PUNCH,
    UNARMED_ABILITY_FORCE_PUNCH, UNARMED_ABILITY_RAPID_STRIKE, SWORD_ABILITY_PARRY, AXE_ABILITY_PARRY, HAMMER_ABILITY_PARRY, IMMORTALITY
}
