package me.Jonathon594.Mythria.Enum;

public enum BlessingType {
    ELIANA_FLIGHT, FELIXIA_NO_WITHER, FELIXIA_HEALING, FELIXIA_INTIMIDATION, FELIXIA_BURN,
    ELIANA_NO_FALL, ELIANA_BREATHING, ELIANA_SUFFOCATE, SELINA_PROSPERITY, SELINA_IMMORTALITY,
    SELINA_INFERTILITY, RAIKA_SPEED, RAIKA_ELECTROCUTE, RAIKA_SMITE, RAIKA_WRATH, MELINIAS_NO_MOBS,
    MELINIAS_WATER_BREATHING, MELINIAS_WATER_JET, MELINIAS_WATER_CURSE, KASAI_NO_MOBS, KASAI_NO_FIRE,
    KASAI_LAVA_JET, KASAI_NETHER_CURSE, ASANA_NO_MOBS, ASANA_NO_EXLODE, ASANA_EARTH_CRUMPLE, ASANA_EARTH_POISON,
    LILASIA_NO_MOBS, LILASIA_SHADOW_HEALING, LILASIA_REINFORCEMENTS, LILASIA_SHADOW_CURSE, MAL_NULLIFY, MAL_CREATION, SELINA_NO_NATURE_MOBS
}
