package me.Jonathon594.Mythria.Enum;

public enum EnumMetalShape {
    INGOT, DOUBLE_INGOT, SHEET, DOUBLE_SHEET, PICK, AXE, SHOVEL, HOE, SWORD, HAMMER, CHISEL, LEGGINGS, CHESTPLATE, HELMET, BOOTS, COIN, BARS, BUCKET, DOOR, SHEARS, FLAT, CLOCK_COMPAS, RAIL, MINECART, SAW, BARDING, NUGGET, SHIELD, DAGGER
}
